using BlankTheSpire.BlankTheSpireCode.Engine;

namespace BlankTheSpire.BlankTheSpireCode.Cards.Forged;

/// <summary>
/// Base for the shipped <c>ForgedCardSlotNN</c> classes (generated by slotgen.py). Each slot is a distinct
/// compiled type — required because BaseLib binds card identity to the .NET Type (PRD §3 / Q1) — but all
/// behaviour comes from data: the ctor asks <see cref="ForgedCards"/> for the slot's <see cref="CardSpec"/>
/// (loaded from user://forged/cards/NN.json), and the shared <see cref="DataCard"/>/EffectRunner do the rest.
/// An unfilled slot resolves to an empty, hidden spec and contributes nothing to the game.
/// </summary>
public abstract class ForgedSlotCard : DataCard
{
    protected ForgedSlotCard(int slot) : base(ForgedCards.SpecForSlot(slot)) { }
}
