// GENERATED by btsgen slotgen.py -- do not edit by hand. Regenerate after changing SLOT_COUNT.
// One distinct compiled type per slot (BaseLib binds card identity to the .NET Type). All slots are
// behaviourless shells: the ctor asks ForgedCards for the slot's CardSpec (user://forged/cards/NN.json).
// Each slot also has a paired ForgedTriggerPowerNN (Phase H3): a card carrying an add_trigger effect grants
// its own slot's power, whose behaviour is read from the same CardSpec (a power's behaviour binds to its Type).

using System.Threading.Tasks;
using BlankTheSpire.BlankTheSpireCode.Engine;
using BlankTheSpire.BlankTheSpireCode.Powers;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;

namespace BlankTheSpire.BlankTheSpireCode.Cards.Forged;

public sealed class ForgedCardSlot01 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot01() : base(1) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower01>(ctx, owner);
}
public sealed class ForgedCardSlot02 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot02() : base(2) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower02>(ctx, owner);
}
public sealed class ForgedCardSlot03 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot03() : base(3) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower03>(ctx, owner);
}
public sealed class ForgedCardSlot04 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot04() : base(4) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower04>(ctx, owner);
}
public sealed class ForgedCardSlot05 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot05() : base(5) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower05>(ctx, owner);
}
public sealed class ForgedCardSlot06 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot06() : base(6) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower06>(ctx, owner);
}
public sealed class ForgedCardSlot07 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot07() : base(7) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower07>(ctx, owner);
}
public sealed class ForgedCardSlot08 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot08() : base(8) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower08>(ctx, owner);
}
public sealed class ForgedCardSlot09 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot09() : base(9) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower09>(ctx, owner);
}
public sealed class ForgedCardSlot10 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot10() : base(10) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower10>(ctx, owner);
}
public sealed class ForgedCardSlot11 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot11() : base(11) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower11>(ctx, owner);
}
public sealed class ForgedCardSlot12 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot12() : base(12) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower12>(ctx, owner);
}
public sealed class ForgedCardSlot13 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot13() : base(13) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower13>(ctx, owner);
}
public sealed class ForgedCardSlot14 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot14() : base(14) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower14>(ctx, owner);
}
public sealed class ForgedCardSlot15 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot15() : base(15) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower15>(ctx, owner);
}
public sealed class ForgedCardSlot16 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot16() : base(16) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower16>(ctx, owner);
}
public sealed class ForgedCardSlot17 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot17() : base(17) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower17>(ctx, owner);
}
public sealed class ForgedCardSlot18 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot18() : base(18) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower18>(ctx, owner);
}
public sealed class ForgedCardSlot19 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot19() : base(19) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower19>(ctx, owner);
}
public sealed class ForgedCardSlot20 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot20() : base(20) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower20>(ctx, owner);
}
public sealed class ForgedCardSlot21 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot21() : base(21) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower21>(ctx, owner);
}
public sealed class ForgedCardSlot22 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot22() : base(22) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower22>(ctx, owner);
}
public sealed class ForgedCardSlot23 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot23() : base(23) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower23>(ctx, owner);
}
public sealed class ForgedCardSlot24 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot24() : base(24) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower24>(ctx, owner);
}
public sealed class ForgedCardSlot25 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot25() : base(25) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower25>(ctx, owner);
}
public sealed class ForgedCardSlot26 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot26() : base(26) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower26>(ctx, owner);
}
public sealed class ForgedCardSlot27 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot27() : base(27) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower27>(ctx, owner);
}
public sealed class ForgedCardSlot28 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot28() : base(28) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower28>(ctx, owner);
}
public sealed class ForgedCardSlot29 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot29() : base(29) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower29>(ctx, owner);
}
public sealed class ForgedCardSlot30 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot30() : base(30) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower30>(ctx, owner);
}
public sealed class ForgedCardSlot31 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot31() : base(31) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower31>(ctx, owner);
}
public sealed class ForgedCardSlot32 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot32() : base(32) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower32>(ctx, owner);
}
public sealed class ForgedCardSlot33 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot33() : base(33) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower33>(ctx, owner);
}
public sealed class ForgedCardSlot34 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot34() : base(34) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower34>(ctx, owner);
}
public sealed class ForgedCardSlot35 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot35() : base(35) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower35>(ctx, owner);
}
public sealed class ForgedCardSlot36 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot36() : base(36) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower36>(ctx, owner);
}
public sealed class ForgedCardSlot37 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot37() : base(37) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower37>(ctx, owner);
}
public sealed class ForgedCardSlot38 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot38() : base(38) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower38>(ctx, owner);
}
public sealed class ForgedCardSlot39 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot39() : base(39) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower39>(ctx, owner);
}
public sealed class ForgedCardSlot40 : ForgedSlotCard, IForgedTriggerHost
{
    public ForgedCardSlot40() : base(40) { }
    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower40>(ctx, owner);
}

// Phase H3: trigger-power shells (one per slot, bound to the slot's CardSpec).
public sealed class ForgedTriggerPower01 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(1); }
public sealed class ForgedTriggerPower02 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(2); }
public sealed class ForgedTriggerPower03 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(3); }
public sealed class ForgedTriggerPower04 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(4); }
public sealed class ForgedTriggerPower05 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(5); }
public sealed class ForgedTriggerPower06 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(6); }
public sealed class ForgedTriggerPower07 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(7); }
public sealed class ForgedTriggerPower08 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(8); }
public sealed class ForgedTriggerPower09 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(9); }
public sealed class ForgedTriggerPower10 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(10); }
public sealed class ForgedTriggerPower11 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(11); }
public sealed class ForgedTriggerPower12 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(12); }
public sealed class ForgedTriggerPower13 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(13); }
public sealed class ForgedTriggerPower14 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(14); }
public sealed class ForgedTriggerPower15 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(15); }
public sealed class ForgedTriggerPower16 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(16); }
public sealed class ForgedTriggerPower17 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(17); }
public sealed class ForgedTriggerPower18 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(18); }
public sealed class ForgedTriggerPower19 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(19); }
public sealed class ForgedTriggerPower20 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(20); }
public sealed class ForgedTriggerPower21 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(21); }
public sealed class ForgedTriggerPower22 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(22); }
public sealed class ForgedTriggerPower23 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(23); }
public sealed class ForgedTriggerPower24 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(24); }
public sealed class ForgedTriggerPower25 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(25); }
public sealed class ForgedTriggerPower26 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(26); }
public sealed class ForgedTriggerPower27 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(27); }
public sealed class ForgedTriggerPower28 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(28); }
public sealed class ForgedTriggerPower29 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(29); }
public sealed class ForgedTriggerPower30 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(30); }
public sealed class ForgedTriggerPower31 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(31); }
public sealed class ForgedTriggerPower32 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(32); }
public sealed class ForgedTriggerPower33 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(33); }
public sealed class ForgedTriggerPower34 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(34); }
public sealed class ForgedTriggerPower35 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(35); }
public sealed class ForgedTriggerPower36 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(36); }
public sealed class ForgedTriggerPower37 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(37); }
public sealed class ForgedTriggerPower38 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(38); }
public sealed class ForgedTriggerPower39 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(39); }
public sealed class ForgedTriggerPower40 : ForgedTriggerPower { protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot(40); }
