"""Codegen: emit the fixed sets of behaviourless shell classes for the data-driven runtimes.

Two shippable runtimes need a fixed pool of distinct compiled .NET Types (BaseLib binds card/character
identity to the Type, Q1; counts are fixed because pools freeze at init, Q2):

  * ForgedCardSlotNN          (P1/P2) — generic forged cards in BLANK the spire's own pool.
  * Forged CLASS shells       (P3/B)  — N self-contained classes, each its own selectable character with an
                                        ISOLATED card pool + a block of card slots bound to that pool.

Each shell carries NO data: its ctor pulls a CardSpec/CharacterSpec from JSON at load via ForgedCards /
ForgedCharacters. Keep the counts in sync with ForgedCards.SlotCount / ForgedCharacters.ClassCount /
ForgedCharacters.CardsPerClass. Pure stdlib. Run:
    python generation/btsgen/slotgen.py
"""
from __future__ import annotations
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FORGED_DIR = ROOT / "mod" / "BlankTheSpireCode" / "Cards" / "Forged"

# --- forged card slots (BLANK the spire's shared pool) -------------------------------------------
SLOT_COUNT = 40  # must equal ForgedCards.SlotCount
CARD_SLOTS_OUT = FORGED_DIR / "ForgedCardSlots.g.cs"

CARD_SLOTS_HEADER = """// GENERATED by btsgen slotgen.py -- do not edit by hand. Regenerate after changing SLOT_COUNT.
// One distinct compiled type per slot (BaseLib binds card identity to the .NET Type). All slots are
// behaviourless shells: the ctor asks ForgedCards for the slot's CardSpec (user://forged/cards/NN.json).
// Each slot also has a paired ForgedTriggerPowerNN (Phase H3): a card carrying an add_trigger effect grants
// its own slot's power, whose behaviour is read from the same CardSpec (a power's behaviour binds to its Type).

using System.Threading.Tasks;
using BlankTheSpire.BlankTheSpireCode.Engine;
using BlankTheSpire.BlankTheSpireCode.Powers;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;

namespace BlankTheSpire.BlankTheSpireCode.Cards.Forged;

"""

CARD_SLOT_LINE = (
    "public sealed class ForgedCardSlot{n:02} : ForgedSlotCard, IForgedTriggerHost\n"
    "{{\n"
    "    public ForgedCardSlot{n:02}() : base({n}) {{ }}\n"
    "    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedTriggerPower{n:02}>(ctx, owner);\n"
    "}}"
)
# Phase H3: one trigger-power shell per card slot, bound to the same slot's CardSpec.
TRIGGER_POWER_LINE = (
    "public sealed class ForgedTriggerPower{n:02} : ForgedTriggerPower "
    "{{ protected override CardSpec? SourceSpec => ForgedCards.SpecForSlot({n}); }}"
)

# --- forged class shells (isolated per-class pools) ----------------------------------------------
CLASS_COUNT = 4       # must equal ForgedCharacters.ClassCount
CARDS_PER_CLASS = 40  # must equal ForgedCharacters.CardsPerClass
CLASSES_OUT = FORGED_DIR / "ForgedClasses.g.cs"

CLASSES_HEADER = """// GENERATED by btsgen slotgen.py -- do not edit by hand.
// Regenerate after changing ForgedCharacters.ClassCount / CardsPerClass.
//
// The forged CLASS runtime (Phase B). Per class K: one isolated CardPool, one [Pool]-bound abstract card base
// (its [Pool] OVERRIDES DataCard's, so the class's cards stick to THIS pool), CardsPerClass behaviourless
// card-slot shells, and one selectable PlaceholderCharacterModel. All data is read from JSON at load via
// ForgedCharacters; unfilled classes hide themselves from character select and their card slots stay empty.

using System.Threading.Tasks;
using BaseLib.Abstracts;
using BaseLib.Utils;
using BlankTheSpire.BlankTheSpireCode.Character;
using BlankTheSpire.BlankTheSpireCode.Engine;
using BlankTheSpire.BlankTheSpireCode.Extensions;
using BlankTheSpire.BlankTheSpireCode.Powers;
using Godot;
using MegaCrit.Sts2.Core.Entities.Characters;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.Cards;
using MegaCrit.Sts2.Core.Models.Relics;

namespace BlankTheSpire.BlankTheSpireCode.Cards.Forged;

"""

POOL_AND_BASE_TMPL = """public sealed class ForgedClassPool{k:02} : CustomCardPoolModel
{{
    public override string Title => "BlankTheSpireForgedClass{k:02}";
    public override string BigEnergyIconPath => "charui/big_energy.png".ImagePath();
    public override string TextEnergyIconPath => "charui/text_energy.png".ImagePath();
    public override float H => ForgedCharacters.SpecForClass({k}).PoolH;
    public override float S => ForgedCharacters.SpecForClass({k}).PoolS;
    public override float V => ForgedCharacters.SpecForClass({k}).PoolV;
    public override Color DeckEntryCardColor => new("ffffff");
    public override bool IsColorless => false;
}}

// This [Pool] overrides DataCard's [Pool(BlankTheSpireCardPool)] for every subclass below.
[Pool(typeof(ForgedClassPool{k:02}))]
public abstract class ForgedClass{k:02}Card : DataCard
{{
    protected ForgedClass{k:02}Card(int slot) : base(ForgedCharacters.CardSpecFor({k}, slot)) {{ }}
}}
"""

CLASS_CARD_LINE = (
    "public sealed class ForgedClass{k:02}Card{n:02} : ForgedClass{k:02}Card, IForgedTriggerHost, IForgedOrbHost, IForgedStatusHost, IForgedSummonHost\n"
    "{{\n"
    "    public ForgedClass{k:02}Card{n:02}() : base({n}) {{ }}\n"
    "    public Task ApplyTrigger(PlayerChoiceContext ctx, Player owner) => ForgedTriggerPower.Apply<ForgedClass{k:02}TriggerPower{n:02}>(ctx, owner);\n"
    "    public int OrbClass => {k}; // Phase I: channel_orb on this card resolves against class {k}'s orb pool\n"
    "    public int StatusClass => {k}; // Phase J: apply_status_custom resolves against class {k}'s status pool\n"
    "    public int SummonClass => {k}; // Phase K: summon resolves against class {k}'s summon pool\n"
    "}}")
# Phase H3: one trigger-power shell per class card slot, bound to that class card's CardSpec.
CLASS_TRIGGER_POWER_LINE = (
    "public sealed class ForgedClass{k:02}TriggerPower{n:02} : ForgedTriggerPower "
    "{{ protected override CardSpec? SourceSpec => ForgedCharacters.CardSpecFor({k}, {n}); }}")
# Phase I: forged-orb shells (M = 1..ORBS_PER_CLASS per class). Each is its own compiled CustomOrbModel type
# (Q1) and reads its OrbSpec from the class's orb_pool via ForgedCharacters.OrbSpecFor(K, M). Shells whose class
# declares fewer custom orbs have a null Source and stay inert (registered but never channeled).
ORBS_PER_CLASS = 3  # must equal ForgedCharacters.MaxCustomOrbs
CLASS_ORB_LINE = (
    "public sealed class ForgedClass{k:02}Orb{m} : ForgedOrb "
    "{{ protected override int OrbClass => {k}; protected override int OrbIndex => {m}; }}")
# Phase J: forged-status shells (M = 1..STATUSES_PER_CLASS per class). Each is its own compiled CustomPowerModel
# type (Q1) and reads its StatusSpec from the class's status_pool via ForgedCharacters.StatusSpecFor(K, M). The
# leaf supplies its own concrete type to ApplyStacks (the generic power apply needs the type at the call site).
STATUSES_PER_CLASS = 4  # must equal ForgedCharacters.MaxCustomStatuses
CLASS_STATUS_LINE = (
    "public sealed class ForgedClass{k:02}Status{m} : ForgedStatusPower\n"
    "{{\n"
    "    protected override int StatusClass => {k};\n"
    "    protected override int StatusIndex => {m};\n"
    "    public override Task ApplyStacks(PlayerChoiceContext ctx, Creature target, Creature source, int amount)\n"
    "        => Apply<ForgedClass{k:02}Status{m}>(ctx, target, source, amount);\n"
    "}}")
# Phase K: forged-summon shells (M = 1..SUMMONS_PER_CLASS per class). Each is its own compiled CustomPetModel
# type (Q1, the entity) and reads its SummonSpec from the class's summon_pool via ForgedCharacters.SummonSpecFor(K, M).
# Behaviour lives in the single ForgedSummonPower applied to each pet (player pets aren't turn-driven), not here.
SUMMONS_PER_CLASS = 2  # must equal ForgedCharacters.MaxSummons
CLASS_SUMMON_LINE = (
    "public sealed class ForgedClass{k:02}Summon{m} : ForgedSummon "
    "{{ protected override int SummonClass => {k}; protected override int SummonIndex => {m}; }}")
# Phase L: one forged-relic shell per class — its own compiled CustomRelicModel type (Q1), reading its RelicSpec
# from the class via ForgedCharacters.RelicSpecFor(K). Behaviour lives in ForgedRelic (fully qualified so the
# generated file needn't import the Powers namespace).
RELICS_PER_CLASS = 1  # must equal ForgedCharacters.MaxRelics
CLASS_RELIC_LINE = (
    "public sealed class ForgedClass{k:02}Relic : BlankTheSpire.BlankTheSpireCode.Powers.ForgedRelic "
    "{{ protected override int RelicClass => {k}; }}")

CHARACTER_TMPL = """public sealed class ForgedCharacterSlot{k:02} : PlaceholderCharacterModel, IForgedCharacterSlot
{{
    private static CharacterSpec Spec => ForgedCharacters.SpecForClass({k});

    public int ClassSlot => {k};  // IForgedCharacterSlot: lets the splash patch map this model to its slot

    private static readonly Func<CardModel>[] SlotCards =
    {{
{slotcards}
    }};

    public override Color NameColor => new("ffffff");
    public override CharacterGender Gender => CharacterGender.Neutral;
    public override int StartingHp => Spec.MaxHp;

    // Phase G: starting orb slots (0 = not an orb class → no orb HUD). Overrides CharacterModel.BaseOrbSlotCount.
    public override int BaseOrbSlotCount => Spec.OrbSlots;

    public override IEnumerable<CardModel> StartingDeck
    {{
        get
        {{
            var deck = new List<CardModel>();
            foreach (var (slot, count) in Spec.StartingDeck)
            {{
                if (slot < 1 || slot > {cards_per_class}) continue;
                if (ForgedCharacters.CardSpecFor({k}, slot).IsEmpty) continue; // never seed a blank card
                for (int i = 0; i < count; i++) deck.Add(SlotCards[slot - 1]());
            }}
            return deck;
        }}
    }}

    // Phase L: equip the class's forged relic if it declared one, else the default Burning Blood.
    public override IReadOnlyList<RelicModel> StartingRelics =>
        ForgedCharacters.HasForgedRelic({k}) ? [ ModelDb.Relic<ForgedClass{k:02}Relic>() ] : [ ModelDb.Relic<BurningBlood>() ];

    public override CardPoolModel CardPool => ModelDb.CardPool<ForgedClassPool{k:02}>();
    public override RelicPoolModel RelicPool => ModelDb.RelicPool<BlankTheSpireRelicPool>();
    public override PotionPoolModel PotionPool => ModelDb.PotionPool<BlankTheSpirePotionPool>();

    // Track 1 (placeholder identity): a forged class ships no bespoke character art yet, so without these
    // overrides it inherits PlaceholderCharacterModel's IRONCLAD select card + standing model — confusingly
    // making a forged class look like the Ironclad. Point the select-screen icons at the shared neutral "?"
    // placeholder PNGs, and build the in-combat/select MODEL from that flat texture via BaseLib's
    // NCreatureVisualsFactory (it accepts a Texture2D — no .tscn needed), so the Ironclad never appears. The big
    // select-screen background (CustomCharacterSelectBg) is a scene; it's left for the generated-splash work (Track 2).
    public override string? CustomCharacterSelectIconPath => "char_select_char_name.png".CharacterUiPath();
    public override string? CustomCharacterSelectLockedIconPath => "char_select_char_name_locked.png".CharacterUiPath();
    public override string? CustomMapMarkerPath => "map_marker_char_name.png".CharacterUiPath();

    public override MegaCrit.Sts2.Core.Nodes.Combat.NCreatureVisuals? CreateCustomVisuals()
    {{
        // Sprite spike (Tier 1+2): a generated sprite cached at user://forged/characters/{k:02}/sprite.png
        // becomes the standing model (with tween micro-animations via ForgedSpriteAnimator); no sprite →
        // the shared "?" texture as before.
        var forged = ForgedSprite.TryCreateVisuals({k});
        if (forged != null) return forged;
        var tex = Godot.ResourceLoader.Load<Godot.Texture2D>("char_select_char_name.png".CharacterUiPath());
        return tex == null ? null
            : BaseLib.Utils.NodeFactories.NodeFactory<MegaCrit.Sts2.Core.Nodes.Combat.NCreatureVisuals>.CreateFromResource(tex);
    }}

    // Unfilled class: hidden from the vanilla character-select screen until JSON fills it.
    public override bool HideFromVanillaCharacterSelect => Spec.IsEmpty;

    // In-code localization (no .pck rebuild). Pronouns/banter are sensible defaults; the forge only supplies
    // name + description. Order matches CharacterLoc(Title, TitleObject, Description, PronounObject,
    // PronounSubject, PronounPossessive, PossessiveAdjective, AromaPrinciple, EndTurnPingAlive,
    // EndTurnPingDead, EventDeathPrevention, GoldMonologue, CardsModifierTitle, CardsModifierDescription).
    public override List<(string, string)>? Localization => Spec.IsEmpty ? null
        : (List<(string, string)>)new CharacterLoc(
            Spec.Name, Spec.Name, Spec.Description,
            "them", "they", "theirs", "their",
            "Forged from the effect vocabulary.",
            "Your move.", "...", "Not yet. There is more to compose.", "It all adds up.",
            "Forged", "Composed from the effect vocabulary.");
}}
"""


def gen_card_slots() -> None:
    cards = "\n".join(CARD_SLOT_LINE.format(n=i) for i in range(1, SLOT_COUNT + 1))
    powers = "\n".join(TRIGGER_POWER_LINE.format(n=i) for i in range(1, SLOT_COUNT + 1))
    body = cards + "\n\n// Phase H3: trigger-power shells (one per slot, bound to the slot's CardSpec).\n" + powers
    CARD_SLOTS_OUT.write_text(CARD_SLOTS_HEADER + body + "\n", encoding="utf-8")
    print(f"generated {SLOT_COUNT} forged card slots + {SLOT_COUNT} trigger powers -> {CARD_SLOTS_OUT}")


def gen_classes() -> None:
    blocks: list[str] = []
    for k in range(1, CLASS_COUNT + 1):
        blocks.append(POOL_AND_BASE_TMPL.format(k=k))
        blocks.append("\n".join(CLASS_CARD_LINE.format(k=k, n=n) for n in range(1, CARDS_PER_CLASS + 1)))
        blocks.append("// Phase H3: trigger-power shells for this class's card slots.\n" + "\n".join(
            CLASS_TRIGGER_POWER_LINE.format(k=k, n=n) for n in range(1, CARDS_PER_CLASS + 1)))
        blocks.append("// Phase I: forged-orb shells for this class (each reads OrbSpecFor(K, M)).\n" + "\n".join(
            CLASS_ORB_LINE.format(k=k, m=m) for m in range(1, ORBS_PER_CLASS + 1)))
        blocks.append("// Phase J: forged-status shells for this class (each reads StatusSpecFor(K, M)).\n" + "\n".join(
            CLASS_STATUS_LINE.format(k=k, m=m) for m in range(1, STATUSES_PER_CLASS + 1)))
        blocks.append("// Phase K: forged-summon shells for this class (each reads SummonSpecFor(K, M)).\n" + "\n".join(
            CLASS_SUMMON_LINE.format(k=k, m=m) for m in range(1, SUMMONS_PER_CLASS + 1)))
        blocks.append("// Phase L: forged-relic shell for this class (reads RelicSpecFor(K)).\n"
                      + CLASS_RELIC_LINE.format(k=k))
        slotcards = "\n".join(
            f"        () => ModelDb.Card<ForgedClass{k:02}Card{n:02}>()," for n in range(1, CARDS_PER_CLASS + 1)
        )
        blocks.append(CHARACTER_TMPL.format(k=k, slotcards=slotcards, cards_per_class=CARDS_PER_CLASS))
    CLASSES_OUT.write_text(CLASSES_HEADER + "\n".join(blocks) + "\n", encoding="utf-8")
    # per class: pool+base (2), card slots, trigger powers, orb shells, status shells, summon shells, character (1)
    n_types = CLASS_COUNT * (2 + CARDS_PER_CLASS + CARDS_PER_CLASS + ORBS_PER_CLASS + STATUSES_PER_CLASS + SUMMONS_PER_CLASS + RELICS_PER_CLASS + 1)
    print(f"generated {CLASS_COUNT} forged classes ({n_types} types) -> {CLASSES_OUT}")


def main() -> int:
    FORGED_DIR.mkdir(parents=True, exist_ok=True)
    gen_card_slots()
    gen_classes()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
