<#
.SYNOPSIS
    Stage the Steam Workshop workspace for BLANK the spire.

.DESCRIPTION
    Populates workshop\workspace\content\ with exactly what the Workshop item ships:

        BlankTheSpire.dll, BlankTheSpire.json, BlankTheSpire.pck

    Unlike the release zip (mod\tools\package_release.ps1), BaseLib is NOT bundled - on the
    Workshop it is a declared dependency (workshop.json "dependencies"), so subscribers get
    Alchyr's own listing automatically and we never redistribute his binaries.

    Source of truth is the *deployed* game mods folder (the proven-good artifact), not raw
    build output. The staged manifest is version-stamped; the working tree is untouched.

    Also refreshes workshop.json in place:
      - description  <- workshop\DESCRIPTION.bbcode (canonical copy; edit that, not the JSON)
      - changeNote   <- "v<Version> - <ChangeNote>"

    Then upload with Steam running, logged into the account that owns STS2:

        ModUploader.exe upload -w <repo>\workshop\workspace

    NOTE: this stages the runtime files at content\ root, per the uploader template README
    ("content folder for mod files (JSON, PCK, DLL)"). If the template workspace generated by
    ModUploader.exe shows a nested layout instead, move the files down one level and fix the
    Copy-Item destination below.

.PARAMETER Version
    Release version, e.g. 0.1.7. Stamped into the staged manifest and the changeNote.
    Defaults to the version already in the deployed manifest (stripped of its "v").

.PARAMETER ChangeNote
    Human-readable summary of what changed, appended to the version in workshop.json's
    changeNote. Defaults to "update" (first upload: pass something like "initial Workshop release").

.PARAMETER GameMods
    The Slay the Spire 2 mods folder to source the deployed artifacts from.

.EXAMPLE
    pwsh workshop\build_workspace.ps1 -Version 0.1.7 -ChangeNote "initial Workshop release"
#>
[CmdletBinding()]
param(
    [string]$Version,
    [string]$ChangeNote = "update",
    [string]$GameMods = "C:\Program Files (x86)\Steam\steamapps\common\Slay the Spire 2\mods"
)

$ErrorActionPreference = "Stop"

# repo root = one level up from this script (workshop\ -> repo)
$repoRoot  = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$workspace = Join-Path $PSScriptRoot "workspace"
$srcBlank  = Join-Path $GameMods "BlankTheSpire"

if (-not (Test-Path $srcBlank)) {
    throw "Deployed mod not found: $srcBlank  (build/deploy the mod first, or pass -GameMods)"
}

$runtime = @("BlankTheSpire.dll", "BlankTheSpire.json", "BlankTheSpire.pck")
foreach ($f in $runtime) {
    if (-not (Test-Path (Join-Path $srcBlank $f))) { throw "Missing $f in $srcBlank" }
}

if (-not $Version) {
    $deployed = Get-Content (Join-Path $srcBlank "BlankTheSpire.json") -Raw -Encoding UTF8 | ConvertFrom-Json
    $Version = $deployed.version -replace "^v", ""
    if (-not $Version) { throw "Could not read a version from the deployed manifest; pass -Version" }
}

# Fresh content dir (gitignored; everything in it is derived).
$contentDir = Join-Path $workspace "content"
if (Test-Path $contentDir) { Remove-Item -Recurse -Force $contentDir }
New-Item -ItemType Directory -Force -Path $contentDir | Out-Null

foreach ($f in $runtime) { Copy-Item (Join-Path $srcBlank $f) (Join-Path $contentDir $f) -Force }

# Version-stamp the staged manifest only.
$manifestPath = Join-Path $contentDir "BlankTheSpire.json"
$manifest = Get-Content $manifestPath -Raw -Encoding UTF8 | ConvertFrom-Json
$manifest.version = "v$Version"
$manifest | ConvertTo-Json -Depth 10 | Set-Content $manifestPath -Encoding utf8

# Refresh workshop.json: description from the canonical BBCode file, changeNote from params.
$workshopJsonPath = Join-Path $workspace "workshop.json"
$descPath         = Join-Path $PSScriptRoot "DESCRIPTION.bbcode"
# -Encoding UTF8 everywhere: these files are BOM-less UTF-8 with real em-dashes, and
# Windows PowerShell 5.1 otherwise decodes BOM-less files as ANSI and mangles them.
$workshopJson = Get-Content $workshopJsonPath -Raw -Encoding UTF8 | ConvertFrom-Json
$workshopJson.description = (Get-Content $descPath -Raw -Encoding UTF8).Trim()
$workshopJson.changeNote  = "v$Version - $ChangeNote"
$workshopJson | ConvertTo-Json -Depth 10 | Set-Content $workshopJsonPath -Encoding utf8

# Preflight the thumbnail (required by the uploader, Steam caps it at 1MB).
$thumb = Join-Path $workspace "image.png"
if (-not (Test-Path $thumb)) {
    Write-Warning "No thumbnail at $thumb - the uploader requires image.png (< 1MB)."
} elseif ((Get-Item $thumb).Length -ge 1MB) {
    Write-Warning "image.png is $([math]::Round((Get-Item $thumb).Length / 1KB)) KB - Steam rejects thumbnails >= 1MB."
}

Write-Host ""
Write-Host "Staged workshop workspace (v$Version)" -ForegroundColor Green
Write-Host "  content\   $($runtime -join ', ')"
Write-Host "  changeNote `"v$Version - $ChangeNote`""
Write-Host ""
Write-Host "Upload (Steam must be running):"
Write-Host "  ModUploader.exe upload -w `"$workspace`""
